services:
  wp:
    container_name: wp
    build:
      context: .
      dockerfile: ./docker/wp/Dockerfile
    volumes:
      - ./public_html:/var/www/html/
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
  
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./docker/node:/var/www/html/
      - ./public_html:/var/www/html/wp
    working_dir: /var/www/html/
    depends_on:
      - wp
    tty: true
    command: npx tailwindcss -i ./input.css -o ./wp/wp-content/themes/tailwind.css --watch